# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Elixir Podcast
email: elixir.podcast.info@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Elixir Devs
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://elixirpodcast.com" # the base hostname & protocol for your site
twitter_username: elixir_podcast
github_username: elixirpodcast

# Build settings
markdown: kramdown

# Extra
exclude: [README.md, package.json, bower.json, Gruntfile.js, node_modules, .bowerrc]
